---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1607581/public_html//tekpen.fipb-ubmg.ac.id/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH